### ISSUE TITLE
Suggestion: extend the list of settings

### ISSUE THREAD

**Issue by wrager** [paulhoughton/vscode-jscpd#1]
In jscpd there are several useful options:

```
-f, --files STRING     glob pattern for find code
    --skip-comments    skip comments in code
-b, --blame BOOLEAN    blame authors of duplications (get information about authors from git)
    --languages-exts STRING list of languages with file extensions (language:ext1,ext2;language:ext3)
-g, --languages STRING list of languages which scan for duplicates, separated with comma
```

It would be nice to have these options in your extension.

* We can bypass the `files` option using the inverted `exclude` option.
* The `languages-exts` option does not exist in [jscpd 0.6.5](https://github.com/kucherenko/jscpd/tree/7e98e1bd9502eadadb1ee522dbe110535e719a54), but it is not necessary.

**Comment by paulhoughton** [comment]
Blame needs a bit more thought regarding the UI but I've added the others.
