### ISSUE TITLE
Update to newer jscpd version

### ISSUE THREAD

**Issue by ysae** [paulhoughton/vscode-jscpd#2]
Please, update version of `jscpd` in dependencies.
Scala language had been added to jscpd [since 0.6.12](https://github.com/kucherenko/jscpd/issues/99#issuecomment-316337562).
And this extension depend on the older version (0.6.5).

**Comment by paulhoughton** [comment]
Updated version has been published

**Comment by ysae** [comment]
Thank you very much!
