### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by rraallvv** [paulhoughton/vscode-jscpd#3]
I installed the extension but when I run it as it's shown on the image from the README nothing happens, any guidance is appreciated.

**Comment by rraallvv** [comment]
It seems the extension doesn't work, each time I run it I see an error at the bottom right side of the window that says "Running the contributed command:'extension.jscpd' failed."

Extension version is 0.3.0
VSC version is 1.23.1

**Comment by paulhoughton** [comment]
Sorry to hear that, seems to be working correctly for me with the same versions.

Can you Toggle Developer Tools from the Help Menu then try again and see if there's any useful error messages in the Console?

Is the behaviour any different if you right click on a folder in the Explorer and select *Copy/Paste Detector*?

**Comment by rraallvv** [comment]
I opened the console as you suggested a tried to run the extension again, and it works just fine, weird!

Then, I tried again without the console, and also restarting the IDE and everything seems normal now.

Thanks, it's very much appreciated.
