### ISSUE TITLE
No duplicates found when customizing languagesExts and files properties.

### ISSUE THREAD

**Issue by evgygor** [paulhoughton/vscode-jscpd#4]
I configured the extension to:
    "jscpd.languagesExts": "python:brs",
    "jscpd.files": "**/*.brs"

The result is "0 duplicated lines out of 0 total lines of code."
I printed the extension's config variable from extension.js:
`{
   "reporter":"json",
   "path":"c:\\Git_work\\main\\DFW",
   "exclude":[
      "**/*.min.js",
      "**/node_modules/**"
   ],
   "min-lines":5,
   "min-tokens":70,
   "files":"**/*.brs",
   "languages-ext":"python:brs"
}`

But using the jscpd cli `jscpd --files="**/*.brs" --languages-exts="python:brs"` works well.

**Comment by paulhoughton** [comment]
languagesExts was incorrectly configured, this should now be fixed.

**Comment by evgygor** [comment]
> languagesExts was incorrectly configured, this should now be fixed.

You mean I need to change the configuration?

**Comment by paulhoughton** [comment]
I've pushed a fix, no changes required for you.

**Comment by evgygor** [comment]
It works now!
Thanks.
