### ISSUE TITLE
Run from context menu (right click on directory/file) doesn't works well

### ISSUE THREAD

**Issue by evgygor** [paulhoughton/vscode-jscpd#5]
Right click on specific directory/file and choose "Copy/Past Detector" performs detection
on whole directory where appropriate directory/file exits. 
Instead of  "dive in",  it's "looks around".

Thanks

**Comment by paulhoughton** [comment]
This should be fixed in latest release

**Comment by evgygor** [comment]
It fixed well on directory level.
When I checking single file, it still checking whole directory.
I think it good enough.
Thanks.

**Comment by paulhoughton** [comment]
I intentionally check the directory a file is in as the requirement to check an individual file for duplication seemed rare.

If this is a valid usecase we can easily make the change?

**Comment by evgygor** [comment]
I agree with you. 
Directory check is pretty good.
