### ISSUE TITLE
Is it checking all files of a workspace?

### ISSUE THREAD

**Issue by crystalfp** [paulhoughton/vscode-jscpd#8]
Thanks for the extension! I have only two quick questions:

1) If I set the LanguageExt parameter to "javascript:js", is vscode-jscpd checking all _js_ files of the workspace?
Otherwise, how should I configure it?

2) Is the check done file by file or it detects duplications appearing between different files? I ask this also because the total source lines reported is suspiciously low.

Thanks for your help!
mario

**Comment by paulhoughton** [comment]
If you run Copy/ Paste Detector from the Command Palette it will check the entire workspace. Alternatively right click on a folder in the explorer to just check below here.

Duplications are for within the same file as well as different ones, this extension just wraps [jscpd](https://github.com/kucherenko/jscpd) where you can get more information on how it works.

**Comment by crystalfp** [comment]
Thanks! It is clear now.
